### ISSUE TITLE
Can tantivy be extended as a distributed search engine of rust just like elasticsearch in java ?

### ISSUE THREAD

**Issue by tianyayoucao** [tantivy-search/tantivy#338]
@fulmicoton  Hi, tantivy really is a handsome project, do you have the plan making it a distributed search engine? Thanks & Regards!

**Comment by fulmicoton** [comment]
The question in the title and the question in the body of the issue are very different.

Tantivy can be extended as a distributed search engine. In fact a lot of the design choice are made while keeping in mind to never "close that door".

I am however not planning to implement that myself at least in the near future. There is a project that [might interest you](https://github.com/hntd187/toshi ) though.

**Comment by tianyayoucao** [comment]
Okey，thanks for your quick reply！Never "close that door"，that's the point !
